// GENERATED-equivalent of desktop/qml/ActivityTypes.qml (itself generated by
// tools/gen_activity_qml.py from assets/activity_types.json). The Android app previously had
// no per-sport colour at all (LogListScreen tints every activity glyph with the theme muted
// colour), so the Calendar/Totals ports - which are all ABOUT per-sport colour - need the
// same 84-entry id->{name,colour} table and the same name-resolution the desktop pages rely
// on (ActivityTypes.forName()). Only the colour+name+id are ported here, not the SVG glyphs:
// Android draws activity icons from Icon.tsx's own monochrome set (see LogListScreen's
// activityIconName), and nothing on Android renders the per-sport SVG the way desktop's
// ActivityBadge does. Keep this in sync with assets/activity_types.json if that file changes.

import { IconName } from '../components/ui/Icon';

export interface ActivityType {
  id: number;
  name: string;
  color: string;
}

export const ACTIVITY_TYPES: Record<number, ActivityType> = {
  1: { id: 1, name: "Unspecified sport", color: "#9d9d9d" },
  2: { id: 2, name: "Multisport", color: "#ade539" },
  3: { id: 3, name: "Running", color: "#f3cd06" },
  4: { id: 4, name: "Cycling", color: "#f47830" },
  5: { id: 5, name: "Mountain biking", color: "#f47830" },
  6: { id: 6, name: "Pool swimming", color: "#1986e7" },
  8: { id: 8, name: "Roller skating", color: "#ade539" },
  9: { id: 9, name: "Aerobics", color: "#fa1b4f" },
  10: { id: 10, name: "Yoga / pilates", color: "#fa1b4f" },
  11: { id: 11, name: "Trekking", color: "#19b251" },
  12: { id: 12, name: "Walking", color: "#19b251" },
  13: { id: 13, name: "Sailing", color: "#1986e7" },
  14: { id: 14, name: "Kayaking", color: "#1986e7" },
  15: { id: 15, name: "Rowing", color: "#1986e7" },
  16: { id: 16, name: "Climbing", color: "#19b251" },
  17: { id: 17, name: "Indoor cycling", color: "#f47830" },
  18: { id: 18, name: "Circuit training", color: "#fa1b4f" },
  19: { id: 19, name: "Triathlon", color: "#ade539" },
  20: { id: 20, name: "Alpine skiing", color: "#2a67e3" },
  21: { id: 21, name: "Snowboarding", color: "#2a67e3" },
  22: { id: 22, name: "Cross-country skiing", color: "#2a67e3" },
  23: { id: 23, name: "Weight training", color: "#fa1b4f" },
  24: { id: 24, name: "Basketball", color: "#9b5cff" },
  25: { id: 25, name: "Soccer / football", color: "#9b5cff" },
  26: { id: 26, name: "Ice hockey", color: "#9b5cff" },
  27: { id: 27, name: "Volleyball", color: "#9b5cff" },
  28: { id: 28, name: "American football", color: "#9b5cff" },
  29: { id: 29, name: "Softball", color: "#9b5cff" },
  30: { id: 30, name: "Cheerleading", color: "#9b5cff" },
  31: { id: 31, name: "Baseball", color: "#9b5cff" },
  33: { id: 33, name: "Tennis", color: "#9b5cff" },
  34: { id: 34, name: "Badminton", color: "#9b5cff" },
  35: { id: 35, name: "Table tennis", color: "#9b5cff" },
  36: { id: 36, name: "Racquet ball", color: "#9b5cff" },
  37: { id: 37, name: "Squash", color: "#9b5cff" },
  38: { id: 38, name: "Martial arts", color: "#fa1b4f" },
  39: { id: 39, name: "Boxing", color: "#fa1b4f" },
  40: { id: 40, name: "Floorball", color: "#9b5cff" },
  51: { id: 51, name: "Scuba diving", color: "#17b5e7" },
  52: { id: 52, name: "Free diving", color: "#17b5e7" },
  53: { id: 53, name: "Snorkeling", color: "#9d9d9d" },
  54: { id: 54, name: "Surfing", color: "#9d9d9d" },
  55: { id: 55, name: "Swimrun", color: "#9d9d9d" },
  56: { id: 56, name: "Duathlon", color: "#9d9d9d" },
  57: { id: 57, name: "Aquathlon", color: "#9d9d9d" },
  58: { id: 58, name: "Obstacle racing", color: "#ade539" },
  61: { id: 61, name: "Adventure racing", color: "#ade539" },
  62: { id: 62, name: "Bowling", color: "#9b5cff" },
  63: { id: 63, name: "Cricket", color: "#9b5cff" },
  64: { id: 64, name: "Crosstrainer", color: "#fa1b4f" },
  65: { id: 65, name: "Dancing", color: "#fa1b4f" },
  66: { id: 66, name: "Golf", color: "#9b5cff" },
  67: { id: 67, name: "Gymnastics", color: "#fa1b4f" },
  68: { id: 68, name: "Handball", color: "#9b5cff" },
  69: { id: 69, name: "Horseback riding", color: "#19b251" },
  70: { id: 70, name: "Ice skating", color: "#2a67e3" },
  71: { id: 71, name: "Indoor rowing", color: "#fa1b4f" },
  72: { id: 72, name: "Canoeing", color: "#1986e7" },
  73: { id: 73, name: "Motorsports", color: "#ade539" },
  74: { id: 74, name: "Mountaineering", color: "#19b251" },
  75: { id: 75, name: "Orienteering", color: "#ade539" },
  76: { id: 76, name: "Rugby", color: "#9b5cff" },
  78: { id: 78, name: "Ski touring", color: "#2a67e3" },
  79: { id: 79, name: "Stretching", color: "#fa1b4f" },
  80: { id: 80, name: "Telemark skiing", color: "#2a67e3" },
  81: { id: 81, name: "Track and field", color: "#ade539" },
  82: { id: 82, name: "Trail running", color: "#f3cd06" },
  83: { id: 83, name: "Openwater swimming", color: "#1986e7" },
  84: { id: 84, name: "Nordic walking", color: "#19b251" },
  85: { id: 85, name: "Snow shoeing", color: "#2a67e3" },
  86: { id: 86, name: "Windsurfing", color: "#1986e7" },
  87: { id: 87, name: "Kettlebell", color: "#fa1b4f" },
  88: { id: 88, name: "Roller skiing", color: "#ade539" },
  89: { id: 89, name: "Standup paddling", color: "#1986e7" },
  90: { id: 90, name: "Cross training", color: "#ade539" },
  91: { id: 91, name: "Kitesurfing / kiting", color: "#1986e7" },
  92: { id: 92, name: "Paragliding", color: "#19b251" },
  93: { id: 93, name: "Treadmill", color: "#f3cd06" },
  94: { id: 94, name: "Frisbee", color: "#9b5cff" },
  95: { id: 95, name: "Indoor training", color: "#fa1b4f" },
  96: { id: 96, name: "Hiking", color: "#19b251" },
  97: { id: 97, name: "Fishing", color: "#19b251" },
  98: { id: 98, name: "Hunting", color: "#19b251" },
  99: { id: 99, name: "Transition", color: "#9d9d9d" },
};

// desktop ActivityTypes.qml's own _nameAliases - an Ambit "Walk" sport mode and a
// Kailash/Garmin "Walk" activity must resolve to the same id so they share a colour and a
// Totals bucket (see TotalsPage.qml's header comment). Keys/values are already normalised
// (lowercased, punctuation-stripped) the same way forName() normalises its input.
const NAME_ALIASES: Record<string, string> = {
  walk: 'walking',
};

const UNSPECIFIED = ACTIVITY_TYPES[1];

function normalise(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '');
}

// Exact port of desktop ActivityTypes.forName(): case-insensitive, punctuation-insensitive,
// alias-aware, device-independent. Anything unrecognised falls back to "Unspecified sport"
// (id 1) rather than guessing - identical behaviour to the QML, so a mode a user renamed on
// the watch still lands in the right colour/bucket wherever both apps recognise the name.
export function activityForName(name: string | null | undefined): ActivityType {
  if (!name) return UNSPECIFIED;
  let want = normalise(String(name));
  if (NAME_ALIASES[want] !== undefined) want = NAME_ALIASES[want];
  for (const key of Object.keys(ACTIVITY_TYPES)) {
    const e = ACTIVITY_TYPES[Number(key)];
    if (normalise(e.name) === want) return e;
  }
  return UNSPECIFIED;
}

export function colorForName(name: string | null | undefined): string {
  return activityForName(name).color;
}

// ─── Activity icon glyphs (Android's monochrome Icon.tsx set) ──────────────────
// Ported from LogListScreen so both the activity log and the sport-mode list draw the same
// per-sport icon, keyed on the lowercased activity name (ACTIVITY_TYPES[id].name or a log's
// activity_type). Falls back to the generic 'activity' glyph for a name with no dedicated
// codepoint in this app's subset (e.g. swimming/transition) - the colour still tells sports
// apart. André, 2026-08-17.
export const ACTIVITY_ICON_NAMES: Record<string, IconName> = {
  'course à pied':        'running',
  'running':               'running',
  'trail running':         'running',
  'cyclisme':              'cycling',
  'cycling':               'cycling',
  'vtt':                   'cycling',
  'mountain biking':       'cycling',
  'randonnée':             'walking',
  'marche':                'walking',
  'trekking':              'walking',
  'hiking':                'walking',
  'trail':                 'mountain',
  'alpinisme':             'mountain',
  'ski alpin':             'mountain',
  'ski de fond':           'mountain',
  'ski de randonnée':      'mountain',
  'skiing':                'mountain',
  'cross country skiing':  'mountain',
  'snowboard':             'mountain',
};

export function activityIconName(type: string | null | undefined): IconName {
  return ACTIVITY_ICON_NAMES[(type ?? '').toLowerCase()] ?? 'activity';
}
