// GENERATED by tools/gen_android_settings_templates.py - do not edit by hand.
//
// SuuntoLink's own per-screen write templates, resolved through the desktop's
// settings_write.py so the two can never drift. A settings write carries only the entries of
// the screen its field belongs to, which is what keeps the paired phone's BLE bond keys off
// the wire - the whole-blob echo this replaces re-sent them on every single change.
//
// Ambit3 family only. Kailash writes one entry at a time over 0x1201 and needs none of this.

/** Entry ids each screen's write carries, already in the order the watch expects. */
export const AMBIT3_WRITE_TEMPLATES: Record<string, number[]> = {
  "general": [
    37,
    39,
    2,
    5,
    6,
    4,
    34,
    33,
    32,
    3,
    67,
    44,
    20,
    17,
    18
  ],
  "units": [
    1,
    67,
    44,
    19,
    8,
    9,
    15,
    10,
    16,
    11,
    12,
    13,
    14
  ],
  "units_mode": [
    7
  ],
  "personal": [
    28,
    30,
    24,
    29,
    26,
    27,
    25,
    67,
    44
  ]
};

/** Which screen owns a setting. null means it has no write template - refuse the write. */
export const AMBIT3_KEY_TEMPLATE: Record<string, string | null> = {
  "language": "general",
  "date_format": "units",
  "time_format": "units",
  "gps_time_keeping": "general",
  "units_mode": "units_mode",
  "distance_unit": "units",
  "gps_position_format": "general",
  "compass_declination": "general",
  "button_lock_time_mode": "general",
  "button_lock_sport_mode": "general",
  "tones": "general",
  "display_contrast": null,
  "display_dark": "general",
  "backlight_mode": "general",
  "backlight_brightness": "general",
  "storm_alarm": "general",
  "alti_baro_profile": "general",
  "units_orientation": "general",
  "air_pressure_unit": "units",
  "altitude_unit": "units",
  "compass_unit": "units",
  "heartrate_unit": "units",
  "height_unit": "units",
  "temperature_unit": "units",
  "vertical_speed_unit": "units",
  "weight_unit": "units",
  "gender": "personal",
  "birth_date": "personal",
  "body_height": "personal",
  "body_weight": "personal",
  "max_hr": "personal",
  "rest_hr": "personal",
  "activity_level": "personal",
  "plans_source": "general"
};

/** Legal values per enum entry id. An entry holding anything else is dropped from the write,
 *  the way SuuntoLink drops a field it cannot represent rather than re-sending it. */
export const AMBIT3_ENUM_VALUES: Record<number, number[]> = {
  "1": [
    0,
    1
  ],
  "2": [
    0,
    1,
    2
  ],
  "3": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
  ],
  "5": [
    0,
    1
  ],
  "6": [
    0,
    1
  ],
  "7": [
    0,
    1,
    2
  ],
  "8": [
    0,
    1
  ],
  "9": [
    0,
    1
  ],
  "10": [
    0,
    1
  ],
  "11": [
    0,
    1
  ],
  "12": [
    0,
    1
  ],
  "13": [
    0,
    1
  ],
  "14": [
    0,
    1
  ],
  "15": [
    0,
    1
  ],
  "16": [
    0,
    1
  ],
  "17": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16
  ],
  "18": [
    0,
    1
  ],
  "19": [
    0,
    1
  ],
  "20": [
    0,
    1
  ],
  "22": [
    0,
    1
  ],
  "24": [
    0,
    1
  ],
  "33": [
    0,
    1,
    2,
    3
  ],
  "37": [
    0,
    1,
    2
  ],
  "38": [
    0,
    1
  ],
  "44": [
    0,
    1
  ],
  "45": [
    0,
    1,
    2,
    3,
    4,
    5
  ],
  "47": [
    0,
    1,
    2,
    3,
    4,
    5,
    6
  ],
  "52": [
    0,
    1,
    2,
    3
  ],
  "227": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11
  ],
  "234": [
    0,
    1
  ],
  "245": [
    1,
    2,
    3,
    4,
    5,
    6
  ],
  "246": [
    0,
    1
  ],
  "247": [
    1,
    2,
    3,
    4,
    5
  ],
  "248": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11
  ],
  "255": [
    0,
    1,
    2,
    3,
    10,
    11,
    12,
    25,
    69
  ],
  "277": [
    0,
    1,
    2,
    3,
    4,
    5
  ],
  "278": [
    0,
    1,
    2,
    3,
    4,
    5
  ],
  "295": [],
  "296": [
    3
  ],
  "298": [
    0,
    1
  ]
};

/** Entry ids that are plain booleans - representable only as 0 or 1. */
export const AMBIT3_BOOL_ENTRIES: number[] = [21, 32, 35, 36, 39, 50, 58, 59, 91, 225, 299, 305, 309, 324];
