// GENERATED by tools/gen_android_settings_templates.py - do not edit by hand.
//
// Per-device settings tables, each derived from that watch's OWN schema descriptor through the
// desktop's settings_write.py - the same source of truth the desktop renders and writes from,
// so the two apps cannot drift. Entry ids differ per schema family (the Traverse shifts nearly
// every id off the Ambit3's), which is why these are per-device and never hardcoded once.

import type { SettingField } from './AmbitSettingsReader';

/** Field tables, one per schema family. Kailash carries no write plumbing (it writes one entry
 *  at a time over 0x1201, not the Ambit3 family's per-screen 0x1101 templates). */
export const AMBIT3_FIELDS: SettingField[] = [
  {
    "key": "language",
    "entryId": 17,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Dansk"
      },
      {
        "value": 1,
        "label": "Deutsch"
      },
      {
        "value": 2,
        "label": "English"
      },
      {
        "value": 3,
        "label": "Espanol"
      },
      {
        "value": 4,
        "label": "Francais"
      },
      {
        "value": 5,
        "label": "Italiano"
      },
      {
        "value": 6,
        "label": "Nederlands"
      },
      {
        "value": 7,
        "label": "Norsk"
      },
      {
        "value": 8,
        "label": "Portugues"
      },
      {
        "value": 9,
        "label": "Suomi"
      },
      {
        "value": 10,
        "label": "Svenska"
      },
      {
        "value": 11,
        "label": "Chinese"
      },
      {
        "value": 12,
        "label": "Japanese"
      },
      {
        "value": 13,
        "label": "Korean"
      },
      {
        "value": 14,
        "label": "Cestina"
      },
      {
        "value": 15,
        "label": "Polski"
      },
      {
        "value": 16,
        "label": "Russian"
      }
    ],
    "label": "Language",
    "control": "dropdown",
    "screen": "general"
  },
  {
    "key": "date_format",
    "entryId": 1,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "DD.MM."
      },
      {
        "value": 1,
        "label": "MM/DD"
      }
    ],
    "label": "Date",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "time_format",
    "entryId": 19,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "24 hours"
      },
      {
        "value": 1,
        "label": "12 hours"
      }
    ],
    "label": "Time",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "gps_time_keeping",
    "entryId": 20,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "On"
      },
      {
        "value": 1,
        "label": "Off"
      }
    ],
    "label": "GPS time keeping",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "units_mode",
    "entryId": 7,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Metric"
      },
      {
        "value": 1,
        "label": "Imperial"
      },
      {
        "value": 2,
        "label": "Advanced"
      }
    ],
    "label": "Units",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "distance_unit",
    "entryId": 10,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "km"
      },
      {
        "value": 1,
        "label": "miles"
      }
    ],
    "label": "Distance",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "gps_position_format",
    "entryId": 3,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "WGS84 Hd.d\u00b0"
      },
      {
        "value": 1,
        "label": "WGS84 Hd\u00b0m.m'"
      },
      {
        "value": 2,
        "label": "WGS84 Hd\u00b0m's.s"
      },
      {
        "value": 3,
        "label": "UTM"
      },
      {
        "value": 4,
        "label": "MGRS"
      },
      {
        "value": 5,
        "label": "British (BNG)"
      },
      {
        "value": 6,
        "label": "Finnish (ETRS-TM35FIN)"
      },
      {
        "value": 7,
        "label": "Finnish (KKJ)"
      },
      {
        "value": 8,
        "label": "Irish (IG)"
      },
      {
        "value": 9,
        "label": "Swedish (RT90)"
      },
      {
        "value": 10,
        "label": "Swiss (CH1903)"
      },
      {
        "value": 11,
        "label": "UTM - NAD27 Alaska"
      },
      {
        "value": 12,
        "label": "UTM - NAD27 Conus"
      },
      {
        "value": 13,
        "label": "UTM - NAD83"
      },
      {
        "value": 14,
        "label": "New Zealand (NZTM2000)"
      }
    ],
    "label": "GPS position format",
    "control": "dropdown",
    "screen": "general"
  },
  {
    "key": "compass_declination",
    "entryId": 4,
    "byteWidth": 4,
    "kind": "number",
    "float": true,
    "scale": 0.017453292519943295,
    "label": "Compass declination",
    "control": "declination",
    "unit": "\u00b0",
    "screen": "general",
    "min": -90.0,
    "max": 90.0
  },
  {
    "key": "button_lock_time_mode",
    "entryId": 6,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "All buttons"
      },
      {
        "value": 1,
        "label": "Actions only"
      }
    ],
    "label": "Button lock, time mode",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "button_lock_sport_mode",
    "entryId": 5,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "All buttons"
      },
      {
        "value": 1,
        "label": "Actions only"
      }
    ],
    "label": "Button lock, sport mode",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "tones",
    "entryId": 2,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Buttons off"
      },
      {
        "value": 1,
        "label": "All on"
      },
      {
        "value": 2,
        "label": "All off"
      }
    ],
    "label": "Tones",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "display_dark",
    "entryId": 32,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Light"
      },
      {
        "value": 1,
        "label": "Dark"
      }
    ],
    "label": "Display",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "backlight_mode",
    "entryId": 33,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Normal"
      },
      {
        "value": 1,
        "label": "Off"
      },
      {
        "value": 2,
        "label": "Night"
      },
      {
        "value": 3,
        "label": "Toggle"
      }
    ],
    "label": "Backlight mode",
    "control": "dropdown",
    "screen": "general"
  },
  {
    "key": "backlight_brightness",
    "entryId": 34,
    "byteWidth": 1,
    "kind": "number",
    "label": "Backlight brightness",
    "control": "slider",
    "unit": "%",
    "screen": "general",
    "min": 5,
    "max": 100
  },
  {
    "key": "storm_alarm",
    "entryId": 39,
    "byteWidth": 1,
    "kind": "bool",
    "label": "Storm alarm",
    "control": "checkbox",
    "screen": "general"
  },
  {
    "key": "alti_baro_profile",
    "entryId": 37,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Alti"
      },
      {
        "value": 1,
        "label": "Baro"
      },
      {
        "value": 2,
        "label": "Automatic"
      }
    ],
    "label": "Alti-baro profile",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "units_orientation",
    "entryId": 18,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Heading up"
      },
      {
        "value": 1,
        "label": "North up"
      }
    ],
    "label": "Orientation",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "air_pressure_unit",
    "entryId": 8,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "hPa"
      },
      {
        "value": 1,
        "label": "inHg"
      }
    ],
    "label": "Air pressure",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "altitude_unit",
    "entryId": 9,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "m"
      },
      {
        "value": 1,
        "label": "ft"
      }
    ],
    "label": "Altitude",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "compass_unit",
    "entryId": 15,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "degree"
      },
      {
        "value": 1,
        "label": "mil"
      }
    ],
    "label": "Compass",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "heartrate_unit",
    "entryId": 16,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "bpm"
      },
      {
        "value": 1,
        "label": "%"
      }
    ],
    "label": "Heart rate",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "height_unit",
    "entryId": 11,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "cm"
      },
      {
        "value": 1,
        "label": "ft"
      }
    ],
    "label": "Height",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "temperature_unit",
    "entryId": 12,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "\u00b0C"
      },
      {
        "value": 1,
        "label": "\u00b0F"
      }
    ],
    "label": "Temperature",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "vertical_speed_unit",
    "entryId": 13,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "m/min"
      },
      {
        "value": 1,
        "label": "ft/min"
      }
    ],
    "label": "Vertical speed",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "weight_unit",
    "entryId": 14,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "kg"
      },
      {
        "value": 1,
        "label": "lbs"
      }
    ],
    "label": "Weight",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "gender",
    "entryId": 24,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Female"
      },
      {
        "value": 1,
        "label": "Male"
      }
    ],
    "label": "Gender",
    "control": "radio",
    "screen": "personal"
  },
  {
    "key": "birth_date",
    "entryId": 30,
    "byteWidth": 1,
    "kind": "year",
    "label": "Birth year",
    "control": "year",
    "screen": "personal",
    "min": 1900,
    "max": 2026
  },
  {
    "key": "body_height",
    "entryId": 29,
    "byteWidth": 1,
    "kind": "number",
    "label": "Height",
    "control": "number",
    "unit": "cm",
    "screen": "personal",
    "min": 89,
    "max": 241
  },
  {
    "key": "body_weight",
    "entryId": 25,
    "byteWidth": 2,
    "kind": "number",
    "scale": 100,
    "label": "Weight",
    "control": "number",
    "unit": "kg",
    "screen": "personal",
    "min": 30.0,
    "max": 250.0
  },
  {
    "key": "max_hr",
    "entryId": 26,
    "byteWidth": 1,
    "kind": "number",
    "label": "Max heart rate",
    "control": "number",
    "unit": "bpm",
    "screen": "personal",
    "min": 30,
    "max": 240
  },
  {
    "key": "rest_hr",
    "entryId": 27,
    "byteWidth": 1,
    "kind": "number",
    "label": "Rest heart rate",
    "control": "number",
    "unit": "bpm",
    "screen": "personal",
    "min": 30,
    "max": 240
  },
  {
    "key": "activity_level",
    "entryId": 28,
    "byteWidth": 1,
    "kind": "number",
    "scale": 10,
    "choices": [
      {
        "value": 2.0,
        "label": "2 - less than 1 hour"
      },
      {
        "value": 3.0,
        "label": "3 - more than 1 hour"
      },
      {
        "value": 4.0,
        "label": "4 - under 30 minutes per week"
      },
      {
        "value": 5.0,
        "label": "5 - 30-60 minutes per week"
      },
      {
        "value": 6.0,
        "label": "6 - 1-3 hours per week"
      },
      {
        "value": 7.0,
        "label": "7 - over 3 hours per week"
      },
      {
        "value": 7.5,
        "label": "7.5 - 5-7 hours"
      },
      {
        "value": 8.0,
        "label": "8 - 7-9 hours"
      },
      {
        "value": 8.5,
        "label": "8.5 - 9-11 hours"
      },
      {
        "value": 9.0,
        "label": "9 - 11-13 hours"
      },
      {
        "value": 9.5,
        "label": "9.5 - 13-15 hours"
      },
      {
        "value": 10.0,
        "label": "10 - over 15 hours"
      }
    ],
    "label": "Activity class",
    "control": "dropdown",
    "step": 1.0,
    "screen": "personal",
    "min": 1.0,
    "max": 10.0
  },
  {
    "key": "plans_source",
    "entryId": 44,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Off"
      },
      {
        "value": 1,
        "label": "Manual"
      }
    ],
    "label": "Use training program",
    "control": "radio"
  }
];

export const TRAVERSE_FIELDS: SettingField[] = [
  {
    "key": "language",
    "entryId": 18,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Dansk"
      },
      {
        "value": 1,
        "label": "Deutsch"
      },
      {
        "value": 2,
        "label": "English"
      },
      {
        "value": 3,
        "label": "Espanol"
      },
      {
        "value": 4,
        "label": "Francais"
      },
      {
        "value": 5,
        "label": "Italiano"
      },
      {
        "value": 6,
        "label": "Nederlands"
      },
      {
        "value": 7,
        "label": "Norsk"
      },
      {
        "value": 8,
        "label": "Portugues"
      },
      {
        "value": 9,
        "label": "Suomi"
      },
      {
        "value": 10,
        "label": "Svenska"
      },
      {
        "value": 11,
        "label": "Chinese"
      },
      {
        "value": 12,
        "label": "Japanese"
      },
      {
        "value": 13,
        "label": "Korean"
      },
      {
        "value": 14,
        "label": "Cestina"
      },
      {
        "value": 15,
        "label": "Polski"
      },
      {
        "value": 16,
        "label": "Russian"
      }
    ],
    "label": "Language",
    "control": "dropdown",
    "screen": "general"
  },
  {
    "key": "date_format",
    "entryId": 1,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "DD.MM."
      },
      {
        "value": 1,
        "label": "MM/DD"
      }
    ],
    "label": "Date",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "time_format",
    "entryId": 20,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "24 hours"
      },
      {
        "value": 1,
        "label": "12 hours"
      }
    ],
    "label": "Time",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "gps_time_keeping",
    "entryId": 21,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "On"
      },
      {
        "value": 1,
        "label": "Off"
      }
    ],
    "label": "GPS time keeping",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "units_mode",
    "entryId": 8,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Metric"
      },
      {
        "value": 1,
        "label": "Imperial"
      },
      {
        "value": 2,
        "label": "Advanced"
      }
    ],
    "label": "Units",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "distance_unit",
    "entryId": 11,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "km"
      },
      {
        "value": 1,
        "label": "miles"
      }
    ],
    "label": "Distance",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "gps_position_format",
    "entryId": 4,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "WGS84 Hd.d\u00b0"
      },
      {
        "value": 1,
        "label": "WGS84 Hd\u00b0m.m'"
      },
      {
        "value": 2,
        "label": "WGS84 Hd\u00b0m's.s"
      },
      {
        "value": 3,
        "label": "UTM"
      },
      {
        "value": 4,
        "label": "MGRS"
      },
      {
        "value": 5,
        "label": "British (BNG)"
      },
      {
        "value": 6,
        "label": "Finnish (ETRS-TM35FIN)"
      },
      {
        "value": 7,
        "label": "Finnish (KKJ)"
      },
      {
        "value": 8,
        "label": "Irish (IG)"
      },
      {
        "value": 9,
        "label": "Swedish (RT90)"
      },
      {
        "value": 10,
        "label": "Swiss (CH1903)"
      },
      {
        "value": 11,
        "label": "UTM - NAD27 Alaska"
      },
      {
        "value": 12,
        "label": "UTM - NAD27 Conus"
      },
      {
        "value": 13,
        "label": "UTM - NAD83"
      },
      {
        "value": 14,
        "label": "New Zealand (NZTM2000)"
      }
    ],
    "label": "GPS position format",
    "control": "dropdown",
    "screen": "general"
  },
  {
    "key": "compass_declination",
    "entryId": 5,
    "byteWidth": 4,
    "kind": "number",
    "float": true,
    "scale": 0.017453292519943295,
    "label": "Compass declination",
    "control": "declination",
    "unit": "\u00b0",
    "screen": "general",
    "min": -90.0,
    "max": 90.0
  },
  {
    "key": "button_lock_time_mode",
    "entryId": 7,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "All buttons"
      },
      {
        "value": 1,
        "label": "Actions only"
      }
    ],
    "label": "Button lock, time mode",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "button_lock_sport_mode",
    "entryId": 6,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "All buttons"
      },
      {
        "value": 1,
        "label": "Actions only"
      }
    ],
    "label": "Button lock, sport mode",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "tones",
    "entryId": 2,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Buttons off"
      },
      {
        "value": 1,
        "label": "All on"
      },
      {
        "value": 2,
        "label": "All off"
      }
    ],
    "label": "Tones",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "display_dark",
    "entryId": 47,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Light"
      },
      {
        "value": 1,
        "label": "Dark"
      }
    ],
    "label": "Display",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "backlight_mode",
    "entryId": 34,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Normal"
      },
      {
        "value": 1,
        "label": "Off"
      },
      {
        "value": 2,
        "label": "Night"
      },
      {
        "value": 3,
        "label": "Toggle"
      }
    ],
    "label": "Backlight mode",
    "control": "dropdown",
    "screen": "general"
  },
  {
    "key": "backlight_brightness",
    "entryId": 35,
    "byteWidth": 1,
    "kind": "number",
    "label": "Backlight brightness",
    "control": "slider",
    "unit": "%",
    "screen": "general",
    "min": 5,
    "max": 100
  },
  {
    "key": "storm_alarm",
    "entryId": 42,
    "byteWidth": 1,
    "kind": "bool",
    "label": "Storm alarm",
    "control": "checkbox",
    "screen": "general"
  },
  {
    "key": "alti_baro_profile",
    "entryId": 41,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Alti"
      },
      {
        "value": 1,
        "label": "Baro"
      },
      {
        "value": 2,
        "label": "Automatic"
      }
    ],
    "label": "Alti-baro profile",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "units_orientation",
    "entryId": 19,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Heading up"
      },
      {
        "value": 1,
        "label": "North up"
      }
    ],
    "label": "Orientation",
    "control": "radio",
    "screen": "general"
  },
  {
    "key": "air_pressure_unit",
    "entryId": 9,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "hPa"
      },
      {
        "value": 1,
        "label": "inHg"
      }
    ],
    "label": "Air pressure",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "altitude_unit",
    "entryId": 10,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "m"
      },
      {
        "value": 1,
        "label": "ft"
      }
    ],
    "label": "Altitude",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "compass_unit",
    "entryId": 16,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "degree"
      },
      {
        "value": 1,
        "label": "mil"
      },
      {
        "value": 2,
        "label": "cardinal"
      }
    ],
    "label": "Compass",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "heartrate_unit",
    "entryId": 17,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "bpm"
      },
      {
        "value": 1,
        "label": "%"
      }
    ],
    "label": "Heart rate",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "height_unit",
    "entryId": 12,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "cm"
      },
      {
        "value": 1,
        "label": "ft"
      }
    ],
    "label": "Height",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "temperature_unit",
    "entryId": 13,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "\u00b0C"
      },
      {
        "value": 1,
        "label": "\u00b0F"
      }
    ],
    "label": "Temperature",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "vertical_speed_unit",
    "entryId": 14,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "m/min"
      },
      {
        "value": 1,
        "label": "ft/min"
      }
    ],
    "label": "Vertical speed",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "weight_unit",
    "entryId": 15,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "kg"
      },
      {
        "value": 1,
        "label": "lbs"
      }
    ],
    "label": "Weight",
    "control": "radio",
    "screen": "units"
  },
  {
    "key": "gender",
    "entryId": 26,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Female"
      },
      {
        "value": 1,
        "label": "Male"
      }
    ],
    "label": "Gender",
    "control": "radio",
    "screen": "personal"
  },
  {
    "key": "birth_date",
    "entryId": 32,
    "byteWidth": 1,
    "kind": "year",
    "label": "Birth year",
    "control": "year",
    "screen": "personal",
    "min": 1900,
    "max": 2026
  },
  {
    "key": "body_height",
    "entryId": 31,
    "byteWidth": 1,
    "kind": "number",
    "label": "Height",
    "control": "number",
    "unit": "cm",
    "screen": "personal",
    "min": 89,
    "max": 241
  },
  {
    "key": "body_weight",
    "entryId": 27,
    "byteWidth": 2,
    "kind": "number",
    "scale": 100,
    "label": "Weight",
    "control": "number",
    "unit": "kg",
    "screen": "personal",
    "min": 30.0,
    "max": 250.0
  },
  {
    "key": "max_hr",
    "entryId": 28,
    "byteWidth": 1,
    "kind": "number",
    "label": "Max heart rate",
    "control": "number",
    "unit": "bpm",
    "screen": "personal",
    "min": 30,
    "max": 240
  },
  {
    "key": "rest_hr",
    "entryId": 29,
    "byteWidth": 1,
    "kind": "number",
    "label": "Rest heart rate",
    "control": "number",
    "unit": "bpm",
    "screen": "personal",
    "min": 30,
    "max": 240
  },
  {
    "key": "activity_level",
    "entryId": 30,
    "byteWidth": 1,
    "kind": "number",
    "scale": 10,
    "choices": [
      {
        "value": 2.0,
        "label": "2 - less than 1 hour"
      },
      {
        "value": 3.0,
        "label": "3 - more than 1 hour"
      },
      {
        "value": 4.0,
        "label": "4 - under 30 minutes per week"
      },
      {
        "value": 5.0,
        "label": "5 - 30-60 minutes per week"
      },
      {
        "value": 6.0,
        "label": "6 - 1-3 hours per week"
      },
      {
        "value": 7.0,
        "label": "7 - over 3 hours per week"
      },
      {
        "value": 7.5,
        "label": "7.5 - 5-7 hours"
      },
      {
        "value": 8.0,
        "label": "8 - 7-9 hours"
      },
      {
        "value": 8.5,
        "label": "8.5 - 9-11 hours"
      },
      {
        "value": 9.0,
        "label": "9 - 11-13 hours"
      },
      {
        "value": 9.5,
        "label": "9.5 - 13-15 hours"
      },
      {
        "value": 10.0,
        "label": "10 - over 15 hours"
      }
    ],
    "label": "Activity class",
    "control": "dropdown",
    "step": 1.0,
    "screen": "personal",
    "min": 1.0,
    "max": 10.0
  },
  {
    "key": "plans_source",
    "entryId": 48,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Off"
      },
      {
        "value": 1,
        "label": "Manual"
      }
    ],
    "label": "Use training program",
    "control": "radio"
  }
];

export const KAILASH_FIELDS: SettingField[] = [
  {
    "key": "date_format",
    "entryId": 1,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "DDMM"
      },
      {
        "value": 1,
        "label": "MMDD"
      }
    ]
  },
  {
    "key": "tones",
    "entryId": 2,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Buttons off"
      },
      {
        "value": 1,
        "label": "All on"
      },
      {
        "value": 2,
        "label": "All off"
      }
    ]
  },
  {
    "key": "vibration",
    "entryId": 3,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Buttons off"
      },
      {
        "value": 1,
        "label": "All on"
      },
      {
        "value": 2,
        "label": "All off"
      }
    ]
  },
  {
    "key": "units_mode",
    "entryId": 7,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Metric"
      },
      {
        "value": 1,
        "label": "Imperial"
      }
    ]
  },
  {
    "key": "language",
    "entryId": 8,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Dansk"
      },
      {
        "value": 1,
        "label": "Deutsch"
      },
      {
        "value": 2,
        "label": "English"
      },
      {
        "value": 3,
        "label": "Espanol"
      },
      {
        "value": 4,
        "label": "Francais"
      },
      {
        "value": 5,
        "label": "Italiano"
      },
      {
        "value": 6,
        "label": "Nederlands"
      },
      {
        "value": 7,
        "label": "Norsk"
      },
      {
        "value": 8,
        "label": "Portugues"
      },
      {
        "value": 9,
        "label": "Suomi"
      },
      {
        "value": 10,
        "label": "Svenska"
      },
      {
        "value": 11,
        "label": "Chinese"
      },
      {
        "value": 12,
        "label": "Japanese"
      },
      {
        "value": 13,
        "label": "Korean"
      },
      {
        "value": 14,
        "label": "Cestina"
      },
      {
        "value": 15,
        "label": "Polski"
      },
      {
        "value": 16,
        "label": "Russian"
      }
    ]
  },
  {
    "key": "time_format",
    "entryId": 9,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "24h"
      },
      {
        "value": 1,
        "label": "12h"
      }
    ]
  },
  {
    "key": "display_contrast",
    "entryId": 15,
    "byteWidth": 1,
    "kind": "number"
  },
  {
    "key": "backlight_mode",
    "entryId": 16,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "Normal"
      },
      {
        "value": 1,
        "label": "Off"
      },
      {
        "value": 2,
        "label": "Night"
      },
      {
        "value": 3,
        "label": "Toggle"
      }
    ]
  },
  {
    "key": "backlight_brightness",
    "entryId": 17,
    "byteWidth": 1,
    "kind": "number"
  },
  {
    "key": "storm_alarm",
    "entryId": 23,
    "byteWidth": 1,
    "kind": "bool"
  },
  {
    "key": "display_dark",
    "entryId": 39,
    "byteWidth": 1,
    "kind": "bool"
  },
  {
    "key": "home_latitude",
    "entryId": 54,
    "byteWidth": 4,
    "kind": "coord",
    "signed": true,
    "scale": 10000000.0
  },
  {
    "key": "home_longitude",
    "entryId": 54,
    "byteWidth": 4,
    "kind": "coord",
    "byteOffset": 4,
    "signed": true,
    "scale": 10000000.0
  },
  {
    "key": "enabled_navigation_systems",
    "entryId": 21,
    "byteWidth": 1,
    "kind": "enum",
    "choices": [
      {
        "value": 0,
        "label": "GPS"
      },
      {
        "value": 1,
        "label": "GPS+Glonass"
      }
    ]
  }
];

/** Entry ids each screen's write carries, in the order the watch expects - per device. */
export const WRITE_TEMPLATES: Record<string, Record<string, number[]>> = {
  "ambit3": {
  "general": [
    37,
    39,
    2,
    5,
    6,
    4,
    34,
    33,
    32,
    3,
    67,
    44,
    20,
    17,
    18
  ],
  "units": [
    1,
    67,
    44,
    19,
    8,
    9,
    15,
    10,
    16,
    11,
    12,
    13,
    14
  ],
  "units_mode": [
    7
  ],
  "personal": [
    28,
    30,
    24,
    29,
    26,
    27,
    25,
    67,
    44
  ]
},
  "traverse": {
  "general": [
    41,
    42,
    2,
    6,
    7,
    5,
    35,
    34,
    47,
    4,
    66,
    48,
    21,
    18,
    19
  ],
  "units": [
    1,
    66,
    48,
    20,
    9,
    10,
    16,
    11,
    17,
    12,
    13,
    14,
    15
  ],
  "units_mode": [
    8
  ],
  "personal": [
    30,
    32,
    26,
    31,
    28,
    29,
    27,
    66,
    48
  ]
}
};

/** Which screen owns a setting (null = no write template, refuse the write) - per device. */
export const KEY_SCREEN: Record<string, Record<string, string | null>> = {
  "ambit3": {
  "language": "general",
  "date_format": "units",
  "time_format": "units",
  "gps_time_keeping": "general",
  "units_mode": "units_mode",
  "distance_unit": "units",
  "gps_position_format": "general",
  "compass_declination": "general",
  "button_lock_time_mode": "general",
  "button_lock_sport_mode": "general",
  "tones": "general",
  "display_dark": "general",
  "backlight_mode": "general",
  "backlight_brightness": "general",
  "storm_alarm": "general",
  "alti_baro_profile": "general",
  "units_orientation": "general",
  "air_pressure_unit": "units",
  "altitude_unit": "units",
  "compass_unit": "units",
  "heartrate_unit": "units",
  "height_unit": "units",
  "temperature_unit": "units",
  "vertical_speed_unit": "units",
  "weight_unit": "units",
  "gender": "personal",
  "birth_date": "personal",
  "body_height": "personal",
  "body_weight": "personal",
  "max_hr": "personal",
  "rest_hr": "personal",
  "activity_level": "personal",
  "plans_source": "general"
},
  "traverse": {
  "language": "general",
  "date_format": "units",
  "time_format": "units",
  "gps_time_keeping": "general",
  "units_mode": "units_mode",
  "distance_unit": "units",
  "gps_position_format": "general",
  "compass_declination": "general",
  "button_lock_time_mode": "general",
  "button_lock_sport_mode": "general",
  "tones": "general",
  "display_dark": "general",
  "backlight_mode": "general",
  "backlight_brightness": "general",
  "storm_alarm": "general",
  "alti_baro_profile": "general",
  "units_orientation": "general",
  "air_pressure_unit": "units",
  "altitude_unit": "units",
  "compass_unit": "units",
  "heartrate_unit": "units",
  "height_unit": "units",
  "temperature_unit": "units",
  "vertical_speed_unit": "units",
  "weight_unit": "units",
  "gender": "personal",
  "birth_date": "personal",
  "body_height": "personal",
  "body_weight": "personal",
  "max_hr": "personal",
  "rest_hr": "personal",
  "activity_level": "personal",
  "plans_source": "general"
}
};

/** Legal values per enum entry id - per device (entry ids differ, so this must be too). */
export const ENUM_VALUES: Record<string, Record<number, number[]>> = {
  "ambit3": {
  "1": [
    0,
    1
  ],
  "2": [
    0,
    1,
    2
  ],
  "3": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
  ],
  "5": [
    0,
    1
  ],
  "6": [
    0,
    1
  ],
  "7": [
    0,
    1,
    2
  ],
  "8": [
    0,
    1
  ],
  "9": [
    0,
    1
  ],
  "10": [
    0,
    1
  ],
  "11": [
    0,
    1
  ],
  "12": [
    0,
    1
  ],
  "13": [
    0,
    1
  ],
  "14": [
    0,
    1
  ],
  "15": [
    0,
    1
  ],
  "16": [
    0,
    1
  ],
  "17": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16
  ],
  "18": [
    0,
    1
  ],
  "19": [
    0,
    1
  ],
  "20": [
    0,
    1
  ],
  "22": [
    0,
    1
  ],
  "24": [
    0,
    1
  ],
  "33": [
    0,
    1,
    2,
    3
  ],
  "37": [
    0,
    1,
    2
  ],
  "38": [
    0,
    1
  ],
  "44": [
    0,
    1
  ],
  "45": [
    0,
    1,
    2,
    3,
    4,
    5
  ],
  "47": [
    0,
    1,
    2,
    3,
    4,
    5,
    6
  ],
  "52": [
    0,
    1,
    2,
    3
  ],
  "227": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11
  ],
  "234": [
    0,
    1
  ],
  "245": [
    1,
    2,
    3,
    4,
    5,
    6
  ],
  "246": [
    0,
    1
  ],
  "247": [
    1,
    2,
    3,
    4,
    5
  ],
  "248": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11
  ],
  "255": [
    0,
    1,
    2,
    3,
    10,
    11,
    12,
    25,
    69
  ],
  "277": [
    0,
    1,
    2,
    3,
    4,
    5
  ],
  "278": [
    0,
    1,
    2,
    3,
    4,
    5
  ],
  "295": [],
  "296": [
    3
  ],
  "298": [
    0,
    1
  ]
},
  "traverse": {
  "1": [
    0,
    1
  ],
  "2": [
    0,
    1,
    2
  ],
  "3": [
    0,
    1,
    2
  ],
  "4": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
  ],
  "6": [
    0,
    1
  ],
  "7": [
    0,
    1
  ],
  "8": [
    0,
    1,
    2
  ],
  "9": [
    0,
    1
  ],
  "10": [
    0,
    1
  ],
  "11": [
    0,
    1
  ],
  "12": [
    0,
    1
  ],
  "13": [
    0,
    1
  ],
  "14": [
    0,
    1
  ],
  "15": [
    0,
    1
  ],
  "16": [
    0,
    1,
    2
  ],
  "17": [
    0,
    1
  ],
  "18": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16
  ],
  "19": [
    0,
    1
  ],
  "20": [
    0,
    1
  ],
  "21": [
    0,
    1
  ],
  "24": [
    0,
    1
  ],
  "26": [
    0,
    1
  ],
  "34": [
    0,
    1,
    2,
    3
  ],
  "36": [
    0,
    1
  ],
  "40": [
    0,
    1
  ],
  "41": [
    0,
    1,
    2
  ],
  "44": [
    0,
    1
  ],
  "46": [
    0,
    1
  ],
  "48": [
    0,
    1
  ],
  "49": [
    0,
    1,
    2,
    3,
    4,
    5,
    6
  ],
  "54": [
    0,
    1,
    2,
    3
  ],
  "214": [
    0,
    1
  ],
  "224": [
    1,
    2,
    3,
    4,
    5,
    6
  ],
  "225": [
    0,
    1
  ],
  "226": [
    1,
    2,
    3,
    4,
    5
  ],
  "227": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11
  ],
  "234": [
    0,
    1,
    2,
    3,
    10,
    11,
    12,
    25,
    69
  ],
  "257": [
    0,
    1,
    2,
    3,
    4,
    5
  ],
  "258": [
    0,
    1,
    2,
    3,
    4,
    5
  ]
}
};

/** Entry ids that are plain booleans (0/1 only) - per device. */
export const BOOL_ENTRIES: Record<string, number[]> = {
  "ambit3": [
  21,
  32,
  35,
  36,
  39,
  50,
  58,
  59,
  91,
  225,
  299,
  305,
  309,
  324
],
  "traverse": [
  22,
  23,
  37,
  38,
  39,
  42,
  47,
  52,
  60,
  61,
  87,
  212,
  238,
  265
]
};

/** The seven unit fields the watch owns while units_mode is Metric or Imperial - shown but not
 *  editable then (only "Advanced" frees them), the same rule settings_write.py enforces. */
export const MODE_OWNED_UNITS: string[] = [
  "air_pressure_unit",
  "altitude_unit",
  "distance_unit",
  "height_unit",
  "temperature_unit",
  "vertical_speed_unit",
  "weight_unit"
];
