#!/usr/bin/env python3
"""Generates desktop/qml/ActivityTypes.qml from assets/activity_types.json.

The table is data (84 real Suunto activity ids, names, category colours and one SVG symbol
each) and is meant to serve the Android app from the same JSON, so the JSON is the source of
truth and this only renders the QML view of it. Re-run after editing the JSON:

    ./tools/gen_activity_qml.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "assets" / "activity_types.json").read_text())

rows = []
for a in sorted(data, key=lambda x: x["id"]):
    rows.append('        %d: { "id": %d, "name": %s, "color": %s, "style": %s, "svg": %s }'
                % (a["id"], a["id"], json.dumps(a["name"]), json.dumps(a["color"]),
                   json.dumps(a["style"]), json.dumps(a["svg"])))

out = '''pragma Singleton
import QtQuick

// GENERATED by tools/gen_activity_qml.py from assets/activity_types.json - do not edit by
// hand, edit the JSON and re-run.
//
// 84 real Suunto activity ids with their names, category colours and per-activity symbol.
// Sport modes carry their own `activityId` on the watch (custom_modes.py decodes entry
// 0x213), so both colour and symbol are keyed on that rather than on the mode's free-text
// English name. See ActivityBadge.qml for the two `style` values and CREDITS.md for the
// seven Suunto-derived symbols.
QtObject {
    id: root

    readonly property var byId: ({
%s
    })

    // id 1 = "Unspecified sport" (the generic star): the fallback for an activity we have no
    // row for, and for a mode whose activityId the watch never set.
    function forId(id) {
        const e = byId[id];
        return e !== undefined ? e : byId[1];
    }

    // A handful of real Ambit3 default sport-mode names (SuuntoLink's own defaults - see
    // SportModesPage.qml's sportBadgeColor() comment: "Cycling/Indoor training/Pool
    // swimming/Run a route/Running/Trekking/Walk") don't spell themselves the same way as
    // this table's own Suunto ActivityType name, even though they mean the same activity -
    // "Walk" the sport mode vs "Walking" the ActivityType. Confirmed case by case, not a
    // general fuzzy rule: five of those seven defaults (Cycling/Indoor training/Pool
    // swimming/Running/Trekking) already match byId exactly and need no entry here.
    readonly property var _nameAliases: ({
        "walk": "walking"
    })

    // Look an activity up by NAME - real need, 2026-08-11 (André, item 16's list view). An
    // activity read off the watch comes from its GPX, which carries the sport mode's name
    // ("Running", "Triathlon") but no numeric id, so a badge keyed on id alone showed the
    // generic star for everything. Matches case-insensitively and ignores punctuation, since
    // a mode is free text a user may have renamed; anything unrecognised falls back to
    // "Unspecified sport" rather than guessing a sport from a name we do not know. Also
    // key-independent of DEVICE: an Ambit3 sport mode and a Kailash activity assigned the
    // same real name (e.g. "Walk") resolve to the same id here, which is what lets
    // TotalsPage.qml group them into one bucket across devices.
    function forName(name) {
        if (!name) return byId[1];
        let want = String(name).toLowerCase().replace(/[^a-z0-9]/g, "");
        if (_nameAliases[want] !== undefined) want = _nameAliases[want];
        for (const key in byId) {
            const e = byId[key];
            if (e.name.toLowerCase().replace(/[^a-z0-9]/g, "") === want) return e;
        }
        return byId[1];
    }

    function colorForId(id) { return forId(id).color }
    function nameForId(id) { return forId(id).name }

    // An SVG data: URI for one entry with its symbol painted in `paint`. The stored `svg` is
    // a 24x24 fragment that paints itself with #fff, so a substitution is all that is needed
    // - no per-colour files, and Image caches the result.
    function iconUri(entry, paint) {
        if (!entry)
            return "";
        const body = String(entry.svg).split("#fff").join(paint);
        return "data:image/svg+xml;utf8," + encodeURIComponent(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">'
            + body + '</svg>');
    }
}
''' % (",\n".join(rows))

target = ROOT / "desktop" / "qml" / "ActivityTypes.qml"
target.write_text(out)
print("wrote %s (%d activities, %d KB)" % (target, len(data), len(out) // 1024))
