#!/usr/bin/env python3
"""Generate android/src/services/AmbitSettingsTemplates.ts from settings_write.py's own tables.

WHY. The Android app writes a setting by reading the watch's whole settings blob, patching
one field and writing the WHOLE blob back. That re-transmits everything the reply contained -
including the paired phone's BLE bond keys (IdentityResolvingKey / EncodingKey) - on every
single settings change. The desktop stopped doing that on 2026-08-10 by copying SuuntoLink's
own per-screen write templates: a write carries only the entries belonging to the screen the
field is on, and the captures show SuuntoLink never sends the key material at all.

Android needs the same tables, and retyping them would let the two drift. This resolves them
through settings_write.py itself - the same schema, the same ordering, the same enum sets -
and emits TypeScript. If the Python tables change, re-run this; nothing is maintained twice.

    ./tools/gen_android_settings_templates.py            # writes the .ts
    ./tools/gen_android_settings_templates.py --check    # exit 1 if stale, write nothing
"""

import argparse
import json
import os
import sys

import sbem_schema
import settings_write as S

OUT = os.path.join(os.path.dirname(__file__), "..", "android", "src", "services",
                   "AmbitSettingsTemplates.ts")


def resolve(schema, suffix):
    """The entry id a schema-path suffix actually lands on - the group's id when the field is
    packed inside one, exactly as build_write_payload resolves it."""
    field = S._find_field(schema, suffix)
    group_id = S._group_containing(schema, field.fid)
    return group_id if group_id is not None else field.fid


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = ap.parse_args()

    schema = sbem_schema.load(sbem_schema.default_descriptor())

    # Per-screen ordered entry ids. build_write_payload sorts by the schema's own order, so
    # sorting here means Android does not need the schema at all.
    screens = {}
    for name, template in S.AMBIT3_WRITE_TEMPLATES.items():
        ids = sorted({resolve(schema, suffix) for suffix in template},
                     key=lambda eid: S._entry_sort_key(schema, eid))
        screens[name] = ids

    # Which screen owns each writable key. A key with no screen has no write template and
    # must be refused rather than written some other way - that is how the desktop treats
    # Display.Contrast.
    key_screen = {key: S.AMBIT3_KEY_TEMPLATE.get(key) for key in S.AMBIT3_SETTINGS}

    # What _representable() needs, reduced to data: the legal value set for every enum entry,
    # and which entries are plain booleans.
    enums, bools = {}, []
    for eid, field in schema.fields.items():
        values = S._enum_value_set(field)
        if values is not None:
            enums[eid] = sorted(values)
        elif field.base == "bool":
            bools.append(eid)

    body = f"""// GENERATED by tools/gen_android_settings_templates.py - do not edit by hand.
//
// SuuntoLink's own per-screen write templates, resolved through the desktop's
// settings_write.py so the two can never drift. A settings write carries only the entries of
// the screen its field belongs to, which is what keeps the paired phone's BLE bond keys off
// the wire - the whole-blob echo this replaces re-sent them on every single change.
//
// Ambit3 family only. Kailash writes one entry at a time over 0x1201 and needs none of this.

/** Entry ids each screen's write carries, already in the order the watch expects. */
export const AMBIT3_WRITE_TEMPLATES: Record<string, number[]> = {json.dumps(screens, indent=2)};

/** Which screen owns a setting. null means it has no write template - refuse the write. */
export const AMBIT3_KEY_TEMPLATE: Record<string, string | null> = {json.dumps(key_screen, indent=2)};

/** Legal values per enum entry id. An entry holding anything else is dropped from the write,
 *  the way SuuntoLink drops a field it cannot represent rather than re-sending it. */
export const AMBIT3_ENUM_VALUES: Record<number, number[]> = {json.dumps(enums, indent=2)};

/** Entry ids that are plain booleans - representable only as 0 or 1. */
export const AMBIT3_BOOL_ENTRIES: number[] = {json.dumps(sorted(bools))};
"""

    path = os.path.normpath(OUT)
    if args.check:
        current = open(path).read() if os.path.exists(path) else ""
        same = current == body
        print("AmbitSettingsTemplates.ts is up to date" if same
              else "AmbitSettingsTemplates.ts is STALE - re-run without --check")
        return 0 if same else 1

    with open(path, "w") as fh:
        fh.write(body)
    print(f"wrote {os.path.relpath(path)}: {len(screens)} screens, "
          f"{sum(len(v) for v in screens.values())} entry slots, {len(enums)} enums")
    return 0


if __name__ == "__main__":
    sys.exit(main())
