#!/usr/bin/env python3
"""Generates desktop/qml/ActivityTypes.qml from assets/activity_types.json.

The table is data (84 real Suunto activity ids, names, category colours and one SVG symbol
each) and is meant to serve the Android app from the same JSON, so the JSON is the source of
truth and this only renders the QML view of it. Re-run after editing the JSON:

    ./tools/gen_activity_qml.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "assets" / "activity_types.json").read_text())

rows = []
for a in sorted(data, key=lambda x: x["id"]):
    rows.append('        %d: { "id": %d, "name": %s, "color": %s, "style": %s, "svg": %s }'
                % (a["id"], a["id"], json.dumps(a["name"]), json.dumps(a["color"]),
                   json.dumps(a["style"]), json.dumps(a["svg"])))

out = '''pragma Singleton
import QtQuick

// GENERATED by tools/gen_activity_qml.py from assets/activity_types.json - do not edit by
// hand, edit the JSON and re-run.
//
// 84 real Suunto activity ids with their names, category colours and per-activity symbol.
// Sport modes carry their own `activityId` on the watch (custom_modes.py decodes entry
// 0x213), so both colour and symbol are keyed on that rather than on the mode's free-text
// English name. See ActivityBadge.qml for the two `style` values and CREDITS.md for the
// seven Suunto-derived symbols.
QtObject {
    id: root

    readonly property var byId: ({
%s
    })

    // id 1 = "Unspecified sport" (the generic star): the fallback for an activity we have no
    // row for, and for a mode whose activityId the watch never set.
    function forId(id) {
        const e = byId[id];
        return e !== undefined ? e : byId[1];
    }

    function colorForId(id) { return forId(id).color }
    function nameForId(id) { return forId(id).name }

    // An SVG data: URI for one entry with its symbol painted in `paint`. The stored `svg` is
    // a 24x24 fragment that paints itself with #fff, so a substitution is all that is needed
    // - no per-colour files, and Image caches the result.
    function iconUri(entry, paint) {
        if (!entry)
            return "";
        const body = String(entry.svg).split("#fff").join(paint);
        return "data:image/svg+xml;utf8," + encodeURIComponent(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">'
            + body + '</svg>');
    }
}
''' % (",\n".join(rows))

target = ROOT / "desktop" / "qml" / "ActivityTypes.qml"
target.write_text(out)
print("wrote %s (%d activities, %d KB)" % (target, len(data), len(out) // 1024))
